version: '3'

networks:
  backend:
    driver: bridge

services:

### NGINX Server #########################################
    nginx:
      build:
        context: nginx
      volumes:
        - ./:/var/www
#        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ./nginx/sites/:/etc/nginx/sites-available
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      networks:
        - backend

### Portainer ################################################
    portainer:
      image: portainer/portainer
      volumes:
#        - ${DATA_PATH_HOST}/portainer_data:/data
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 9010:9000
      networks:
        - backend
